
baseURL = "https://wordplorer.com/"
languageCode = "en-us"
title = "Wordplorer"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
